jobs:
  include:
    - os: windows
      language: shell
      env: JAVA_HOME="$HOME/.sdkman/candidates/java/current"


before_install:
  - choco install zip unzip
  - choco install visualstudio2017-workload-vctools
  
  - curl -sL https://get.sdkman.io | bash
  - mkdir -p "$HOME/.sdkman/etc/"
  - echo sdkman_auto_answer=true > "$HOME/.sdkman/etc/config"
  - echo sdkman_auto_selfupdate=true >> "$HOME/.sdkman/etc/config"
  - "source $HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java 20.0.0.r11-grl || true
  - gu.cmd install native-image  || true
  - native-image.cmd --version  || true
  - sdk install maven  || true

script:
  - mvn clean
  - SEMVER_LAST_TAG=$(git describe --abbrev=0 --tags 2>/dev/null)
  - if [ -z $SEMVER_LAST_TAG ]; then >&2 echo "No tags defined"; SEMVER_LAST_TAG="0.0.1"; fi;
  - echo mvn install -Dmaven.skip.deploy=true -Drevision=${SEMVER_LAST_TAG} -DbuildNumer=${TRAVIS_BUILD_NUMBER}
  - mvn install -Dmaven.skip.deploy=true -Drevision=${SEMVER_LAST_TAG} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
  - KEECLI_VERSION=$(mvn help:evaluate -N -Dexpression=project.version -Dmaven.skip.deploy=true -Drevision=${SEMVER_LAST_TAG} -DbuildNumer=${TRAVIS_BUILD_NUMBER} |grep -v '\[' | xargs)
  - KEECLI_VERSION=${KEECLI_VERSION}-${TRAVIS_BUILD_NUMBER}
  - echo "${KEECLI_VERSION}"
  - find target -name "*dependencies.jar" -exec mv {} keecli-${KEECLI_VERSION}.jar \;
  - ls ./target -lars
  - ls -lars
  - ./buildnative.bat ./keecli-${KEECLI_VERSION}.jar ./keecli
  - cp /c/Windows/System32/VCRUNTIME140.dll .
  - zip keecli-${KEECLI_VERSION}.zip keecli.exe VCRUNTIME140.dll

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - keecli-${KEECLI_VERSION}.zip
    - keecli-${KEECLI_VERSION}.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true